import Joi from 'joi';

export const jobSchemaValidation = Joi.object({
  user_id: Joi.string().required(),
  jobsTags: Joi.array().items(Joi.string()).required(),
  jobTitle: Joi.string().required(),
  jobHeadline: Joi.string().required(),
  jobDescription: Joi.string().required(),
  attachments: Joi.array().items(Joi.string()),
  links: Joi.array().items(Joi.string()),
  duration: Joi.string(),
  hourly: Joi.number(),
  budget: Joi.string(),
  experience_level: Joi.string(),
  activities: Joi.object({
    proposals: Joi.number().default(0),
    lastViewed: Joi.date(),
    interviewing: Joi.number().default(0),
    invitesSent: Joi.number().default(0),
    unAnsweredInvites: Joi.number().default(0),
  }),
  verified: Joi.boolean().required(),
  rating: Joi.string().required(),
  status: Joi.string().valid('active', 'inactive', 'other').default('inactive'),
  location: Joi.string().required(),
  jobType: Joi.string().required(),
  teamSize: Joi.string().required(),
  industryType: Joi.string().required(),
  industrySize: Joi.string().required(),
  companyType: Joi.string().required(),
  projectType: Joi.string().required(),
  softSkills: Joi.array().items(Joi.string()),
  languages: Joi.array().items(Joi.string()),
  datePosted: Joi.date().default(Date.now),
}).options({ allowUnknown: true, stripUnknown: true, abortEarly: false });

export const jobSchemaUpdateValidation = Joi.object({
  user_id: Joi.string(),
  jobsTags: Joi.array().items(Joi.string()),
  jobTitle: Joi.string(),
  jobHeadline: Joi.string(),
  jobDescription: Joi.string(),
  attachments: Joi.array().items(Joi.string()),
  links: Joi.array().items(Joi.string()),
  duration: Joi.string(),
  hourly: Joi.number(),
  budget: Joi.string(),
  experience_level: Joi.string(),
  activities: Joi.object({
    proposals: Joi.number(),
    lastViewed: Joi.date(),
    interviewing: Joi.number(),
    invitesSent: Joi.number(),
    unAnsweredInvites: Joi.number(),
  }),
  verified: Joi.boolean(),
  rating: Joi.string(),
  status: Joi.string().valid('active', 'inactive', 'other').default('inactive'),
  location: Joi.string(),
  jobType: Joi.string(),
  teamSize: Joi.string(),
  industryType: Joi.string(),
  industrySize: Joi.string(),
  companyType: Joi.string(),
  projectType: Joi.string(),
  softSkills: Joi.array().items(Joi.string()),
  languages: Joi.array().items(Joi.string()),
}).min(1);
