export const jobPayload = [
  {
    jobsTags: ['Responsive designs', 'User interface Design', 'Mobile App Design'],
    jobTitle: 'UI/UX Designer',
    jobSubInfo: 'Hourly: $40-$66-Intermediate- Est. Time:12 Months,Less than 30hrs/week-posted 2hours ago',
    jobDescription:
      'Looking for a figma UI/UX designer who can design a cosmetic mobile and website application.The app consists of 10 screens, and the ideal candidate should have a strong background in designing for mobile applications.',
    verified: true,
    rating: 5,
    location: 'United Kingdom',
    jobType: 'Remote',
    jobSize: 'Small team (4-6 members)',
    status: 'inactive',
  },
  {
    jobsTags: ['Photography', 'Design', 'Mobile App Design'],
    jobTitle: 'Graphic Designer',
    jobSubInfo: 'Hourly: $25-$45-Entry Level- Est. Time:6 Months,Less than 10hrs/week-posted 4hours ago',
    jobDescription: 'We are looking for a talented graphic designer to create eye-catching designs for our print and digital marketing campaigns.',
    verified: true,
    rating: 4,
    location: 'United States',
    jobType: 'Part-time',
    jobSize: 'Individual',
  },
  {
    jobsTags: ['Web Development', 'JavaScript', 'React'],
    jobTitle: 'Front-end Developer',
    jobSubInfo: 'Hourly: $30-$50-Intermediate- Est. Time:6 Months,Less than 20hrs/week-posted 1day ago',
    jobDescription: 'We need a skilled front-end developer to build a responsive web application using React and other modern web technologies.',
    verified: true,
    rating: 4.5,
    location: 'Canada',
    jobType: 'Remote',
    jobSize: 'Small team (2-3 members)',
    uniqueIdentifier: 'job789',
  },
  {
    jobsTags: ['Responsive designs', 'Mobile App Design'],
    jobTitle: 'UI/UX Designer',
    jobSubInfo: 'Hourly: $40-$66-Intermediate- Est. Time:12 Months,Less than 30hrs/week-posted 2hours ago',
    jobDescription:
      'Looking for a figma UI/UX designer who can design a cosmetic mobile and website application.The app consists of 10 screens, and the ideal candidate should have a strong background in designing for mobile applications.',
    verified: true,
    rating: 5,
    location: 'United Kingdom',
    jobType: 'Remote',
    jobSize: 'Small team (4-6 members)',
  },
  {
    jobsTags: ['UI/UX', 'Design', 'Mobile App Design', 'Sketch'],
    jobTitle: 'UI/UX Designer',
    jobSubInfo: 'Hourly: $40-$66-Intermediate- Est. Time:12 Months,Less than 30hrs/week-posted 2hours ago',
    jobDescription:
      'Looking for a sketch UI/UX designer who can design a social media mobile and website application.The app consists of 15 screens, and the ideal candidate should have a strong background in designing for mobile applications.',
    verified: true,
    rating: 4.5,
    location: 'Canada',
    jobType: 'Remote',
    jobSize: 'Medium team (7-10 members)',
  },
  {
    jobsTags: ['Backend Development', 'NodeJS', 'ExpressJS'],
    jobTitle: 'Backend Developer',
    jobSubInfo: 'Hourly: $25-$40-Expert- Est. Time:6 Months,Less than 30hrs/week-posted 1day ago',
    jobDescription:
      'We are looking for a Node.js developer to join our team and help us build and maintain our backend services. The ideal candidate should have experience with Express.js and RESTful APIs.',
    verified: false,
    rating: 4.2,
    location: 'India',
    jobType: 'Remote',
    jobSize: 'Large team (11+ members)',
    status: 'active',
  },
];
