export const skills = {
  'Programming Languages': [
    'Java',
    'Python',
    'JavaScript',
    'C#',
    'Ruby',
    'PHP',
    'Swift',
    'Kotlin',
    'Objective-C',
    'C++',
    'TypeScript',
    'Go',
    'Rust',
    'Perl',
  ],
  'Web Development': [
    'HTML/CSS',
    'JavaScript',
    'jQuery',
    'AngularJS',
    'React',
    'Vue.js',
    'Bootstrap',
    'Node.js',
    'Express.js',
    'Laravel',
    'Django',
    'Flask',
    'Ruby on Rails',
    'ASP.NET',
    'WordPress',
  ],
  'Mobile Development': ['iOS Development (Swift, Objective-C)', 'Android Development (Java, Kotlin)', 'React Native', 'Xamarin', 'Flutter'],
  Database: ['SQL', 'MySQL', 'PostgreSQL', 'Oracle', 'MongoDB', 'Cassandra', 'Redis'],
  'Cloud Computing': ['Amazon Web Services (AWS)', 'Microsoft Azure', 'Google Cloud Platform (GCP)', 'Docker', 'Kubernetes'],
  DevOps: ['Continuous Integration/Continuous Deployment (CI/CD)', 'Jenkins', 'Git', 'GitHub', 'Bitbucket', 'Ansible', 'Puppet', 'Chef'],
  'Artificial Intelligence/Machine Learning': [
    'TensorFlow',
    'Keras',
    'PyTorch',
    'Scikit-learn',
    'Natural Language Processing (NLP)',
    'Computer Vision',
  ],
  Cybersecurity: [
    'Network Security',
    'Penetration Testing',
    'Vulnerability Assessment',
    'Security Information and Event Management (SIEM)',
    'Identity and Access Management (IAM)',
    'Encryption',
  ],
  'Photography Software': [
    'Adobe Photoshop',
    'Adobe Lightroom',
    'Capture One',
    'GIMP',
    'Affinity Photo',
    'Skylum Luminar',
    'DxO PhotoLab',
    'ON1 Photo RAW',
  ],
  'Color Management': ['Color Calibration', 'ICC Profiles', 'Color Spaces', 'Color Management Software (e.g. X-Rite ColorMunki, Datacolor Spyder)'],
  'Digital Asset Management': [
    'File Organization',
    'Backup Strategies',
    'Cloud Storage (e.g. Dropbox, Google Drive, Amazon Photos)',
    'Digital Asset Management Software (e.g. Adobe Bridge, Photo Mechanic, Capture One)',
  ],
  'Image Editing Techniques': [
    'Retouching',
    'Masking',
    'Layers',
    'Selections',
    'Cloning/Healing',
    'Dodging/Burning',
    'Sharpening',
    'Noise Reduction',
  ],
  'Graphic Design Software': ['Adobe Photoshop', 'Adobe Illustrator', 'Adobe InDesign', 'Sketch', 'Figma', 'CorelDRAW', 'Affinity Designer'],
  'User Interface/User Experience Design': ['Adobe XD', 'Figma', 'Sketch', 'InVision Studio', 'Axure', 'Balsamiq'],
  'Web Design': ['HTML/CSS', 'JavaScript', 'Bootstrap', 'WordPress', 'Webflow', 'Wix', 'Squarespace'],
  '3D Design': ['AutoCAD', 'Blender', 'SketchUp', 'Rhino', '3ds Max', 'Maya'],
  'Digital Painting and Illustration': ['Adobe Photoshop', 'Procreate', 'Clip Studio Paint', 'Corel Painter', 'Krita', 'Affinity Photo'],
  'Motion Graphics and Animation': ['Adobe After Effects', 'Cinema 4D', 'Blender', 'Maya', 'Houdini', 'Synfig'],
  Typography: ['Adobe InDesign', 'Adobe Illustrator', 'FontLab Studio', 'Glyphs', 'FontExplorer X'],
};

export const skillsWithOutSection = [
  'Java',
  'Python',
  'JavaScript',
  'C#',
  'Ruby',
  'PHP',
  'Swift',
  'Kotlin',
  'Objective-C',
  'C++',
  'TypeScript',
  'Go',
  'Rust',
  'Perl',
  'HTML/CSS',
  'JavaScript',
  'jQuery',
  'AngularJS',
  'React',
  'Vue.js',
  'Bootstrap',
  'Node.js',
  'Express.js',
  'Laravel',
  'Django',
  'Flask',
  'Ruby on Rails',
  'ASP.NET',
  'WordPress',
  'iOS Development (Swift, Objective-C)',
  'Android Development (Java, Kotlin)',
  'React Native',
  'Xamarin',
  'Flutter',
  'SQL',
  'MySQL',
  'PostgreSQL',
  'Oracle',
  'MongoDB',
  'Cassandra',
  'Redis',
  'Amazon Web Services (AWS)',
  'Microsoft Azure',
  'Google Cloud Platform (GCP)',
  'Docker',
  'Kubernetes',
  'Continuous Integration/Continuous Deployment (CI/CD)',
  'Jenkins',
  'Git',
  'GitHub',
  'Bitbucket',
  'Ansible',
  'Puppet',
  'Chef',
  'TensorFlow',
  'Keras',
  'PyTorch',
  'Scikit-learn',
  'Natural Language Processing (NLP)',
  'Computer Vision',
  'Network Security',
  'Penetration Testing',
  'Vulnerability Assessment',
  'Security Information and Event Management (SIEM)',
  'Identity and Access Management (IAM)',
  'Encryption',
  'Adobe Photoshop',
  'Adobe Lightroom',
  'Capture One',
  'GIMP',
  'Affinity Photo',
  'Skylum Luminar',
  'DxO PhotoLab',
  'ON1 Photo RAW',
  'Color Calibration',
  'ICC Profiles',
  'Color Spaces',
  'Color Management Software (e.g. X-Rite ColorMunki, Datacolor Spyder)',
  'File Organization',
  'Backup Strategies',
  'Cloud Storage (e.g. Dropbox, Google Drive, Amazon Photos)',
  'Digital Asset Management Software (e.g. Adobe Bridge, Photo Mechanic, Capture One)',
  'Retouching',
  'Masking',
  'Layers',
  'Selections',
  'Cloning/Healing',
  'Dodging/Burning',
  'Sharpening',
  'Noise Reduction',
  'Adobe Photoshop',
  'Adobe Illustrator',
  'Adobe InDesign',
  'Sketch',
  'Figma',
  'CorelDRAW',
  'Affinity Designer',
  'Adobe XD',
  'Figma',
  'Sketch',
  'InVision Studio',
  'Axure',
  'Balsamiq',
  'HTML/CSS',
  'JavaScript',
  'Bootstrap',
  'WordPress',
  'Webflow',
  'Wix',
  'Squarespace',
  'AutoCAD',
  'Blender',
  'SketchUp',
  'Rhino',
  '3ds Max',
  'Maya',
  'Adobe Photoshop',
  'Procreate',
  'Clip Studio Paint',
  'Corel Painter',
  'Krita',
  'Affinity Photo',
  'Adobe After Effects',
  'Cinema 4D',
  'Blender',
  'Maya',
  'Houdini',
  'Synfig',
  'Adobe InDesign',
  'Adobe Illustrator',
  'FontLab Studio',
  'Glyphs',
  'FontExplorer X',
];

export const softSkills = [
  'Communication skills',
  'Teamwork and collaboration',
  'Time management',
  'Problem-solving',
  'Decision-making',
  'Leadership',
  'Adaptability',
  'Creativity',
  'Emotional intelligence',
  'Active listening',
  'Conflict resolution',
  'Negotiation skills',
  'Critical thinking',
  'Networking',
  'Interpersonal skills',
  'Empathy',
  'Stress management',
  'Public speaking',
  'Presentation skills',
  'Customer service',
  'Cultural sensitivity and diversity awareness',
  'Positive attitude',
  'Responsibility',
  'Accountability',
  'Motivation',
  'Flexibility',
  'Resilience',
  'Initiative',
  'Coaching and mentoring',
  'Planning and organization',
  'Goal-setting',
  'Self-awareness',
  'Self-confidence',
  'Integrity',
  'Work ethic',
];

export const technicalTools = {
  'Graphic Designing': ['Adobe Photoshop', 'Adobe Illustrator', 'CorelDRAW', 'InDesign', 'Sketch', 'GIMP'],
  'Web Development': [
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
    'Express.js',
    'Django',
    'Ruby on Rails',
    'ASP.NET',
    'PHP',
    'WordPress',
  ],
  'Mobile App Development': ['React Native', 'Flutter', 'Xamarin', 'Swift', 'Java (Android)', 'Kotlin (Android)'],
  'Database Management': ['MySQL', 'Oracle Database', 'Microsoft SQL Server', 'PostgreSQL', 'MongoDB', 'Firebase'],
  'Version Control': ['Git', 'GitHub', 'Bitbucket'],
  'IDEs and Text Editors': ['Visual Studio Code', 'Sublime Text', 'Atom', 'IntelliJ IDEA', 'Eclipse', 'Xcode'],
  'Project Management': ['Jira', 'Trello', 'Asana', 'Basecamp'],
  'Virtualization and Containerization': ['Docker', 'Kubernetes', 'VMware', 'VirtualBox'],
  Networking: ['Wireshark', 'Cisco Packet Tracer', 'Nmap', 'Fiddler'],
  'Machine Learning and Data Science': ['Python', 'R', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'Pandas', 'NumPy', 'Jupyter Notebook'],
  'Cloud Platforms': ['Amazon Web Services (AWS)', 'Microsoft Azure', 'Google Cloud Platform (GCP)'],
};
