export const skills = {
  'Programming Languages': [
    'Java',
    'Python',
    'JavaScript',
    'C#',
    'Ruby',
    'PHP',
    'Swift',
    'Kotlin',
    'Objective-C',
    'C++',
    'TypeScript',
    'Go',
    'Rust',
    'Perl',
  ],
  'Web Development': [
    'HTML/CSS',
    'JavaScript',
    'jQuery',
    'AngularJS',
    'React',
    'Vue.js',
    'Bootstrap',
    'Node.js',
    'Express.js',
    'Laravel',
    'Django',
    'Flask',
    'Ruby on Rails',
    'ASP.NET',
    'WordPress',
  ],
  'Mobile Development': ['iOS Development (Swift, Objective-C)', 'Android Development (Java, Kotlin)', 'React Native', 'Xamarin', 'Flutter'],
  Database: ['SQL', 'MySQL', 'PostgreSQL', 'Oracle', 'MongoDB', 'Cassandra', 'Redis'],
  'Cloud Computing': ['Amazon Web Services (AWS)', 'Microsoft Azure', 'Google Cloud Platform (GCP)', 'Docker', 'Kubernetes'],
  DevOps: ['Continuous Integration/Continuous Deployment (CI/CD)', 'Jenkins', 'Git', 'GitHub', 'Bitbucket', 'Ansible', 'Puppet', 'Chef'],
  'Artificial Intelligence/Machine Learning': [
    'TensorFlow',
    'Keras',
    'PyTorch',
    'Scikit-learn',
    'Natural Language Processing (NLP)',
    'Computer Vision',
  ],
  Cybersecurity: [
    'Network Security',
    'Penetration Testing',
    'Vulnerability Assessment',
    'Security Information and Event Management (SIEM)',
    'Identity and Access Management (IAM)',
    'Encryption',
  ],
  'Photography Software': [
    'Adobe Photoshop',
    'Adobe Lightroom',
    'Capture One',
    'GIMP',
    'Affinity Photo',
    'Skylum Luminar',
    'DxO PhotoLab',
    'ON1 Photo RAW',
  ],
  'Color Management': ['Color Calibration', 'ICC Profiles', 'Color Spaces', 'Color Management Software (e.g. X-Rite ColorMunki, Datacolor Spyder)'],
  'Digital Asset Management': [
    'File Organization',
    'Backup Strategies',
    'Cloud Storage (e.g. Dropbox, Google Drive, Amazon Photos)',
    'Digital Asset Management Software (e.g. Adobe Bridge, Photo Mechanic, Capture One)',
  ],
  'Image Editing Techniques': [
    'Retouching',
    'Masking',
    'Layers',
    'Selections',
    'Cloning/Healing',
    'Dodging/Burning',
    'Sharpening',
    'Noise Reduction',
  ],
  'Graphic Design Software': ['Adobe Photoshop', 'Adobe Illustrator', 'Adobe InDesign', 'Sketch', 'Figma', 'CorelDRAW', 'Affinity Designer'],
  'User Interface/User Experience Design': ['Adobe XD', 'Figma', 'Sketch', 'InVision Studio', 'Axure', 'Balsamiq'],
  'Web Design': ['HTML/CSS', 'JavaScript', 'Bootstrap', 'WordPress', 'Webflow', 'Wix', 'Squarespace'],
  '3D Design': ['AutoCAD', 'Blender', 'SketchUp', 'Rhino', '3ds Max', 'Maya'],
  'Digital Painting and Illustration': ['Adobe Photoshop', 'Procreate', 'Clip Studio Paint', 'Corel Painter', 'Krita', 'Affinity Photo'],
  'Motion Graphics and Animation': ['Adobe After Effects', 'Cinema 4D', 'Blender', 'Maya', 'Houdini', 'Synfig'],
  Typography: ['Adobe InDesign', 'Adobe Illustrator', 'FontLab Studio', 'Glyphs', 'FontExplorer X'],
};
